#!/usr/bin/python3
def find_prime_factors(n):
    factors = []
    divisor = 2
    while n > 1:
        while n % divisor == 0:
            factors.append(divisor)
            n //= divisor
        divisor += 1
    return factors

def main():
    n = int(input("Enter the RSA number (n): "))
    prime_factors = find_prime_factors(n)
    print("Prime factors of", n, "are:", prime_factors)

if __name__ == "__main__":
    main()
